name: 'Compile Mermaid'

on:
  push:
    paths:
      - '**/*.mermaid'
      - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check mmdc version
      run: |
        /node_modules/.bin/mmdc -V

    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mermaid$' | xargs)"

    - name: mermaid files changed
      run: |
        echo ${{ steps.getfile.outputs.files }}

    - name: compile mermaid
      uses: neenjaw/compile-mermaid-markdown-action@update-cli-source
      with:
        files: ${{ steps.getfile.outputs.files }}
        output: 'output'
      env:
        HIDE_CODEBLOCKS: 1
        ABSOLUTE_IMAGE_LINKS: 1

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git commit -m "Add changed markdown and images"
        git status

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: abs_path